baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Junella Marie Caringal Portfolio'
theme = 'pulp'

canonifyurls = true
hasCJKLanguage = true

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Junella Marie Caringal"
avatar = "avatar.jpeg"
favicon = "favicon_profile.ico"
description = "San Francisco based full-stack software engineer, seeking junior and apprenticeship opportunities."
publicationYear = "2022"
custom_css = ["/css/custom.css", "/css/icons.css"]
custom_js = ["/hireMeNavbar.js", "/homeNavbar.js"]

[outputs]
section = ["JSON", "HTML"]
term = ["JSON", "HTML"]

[pages]
mainSections = ["projects"]

[[menu.main]]
identifier = "linkedin"
pre = "<i><img class='contactIcon' src='/images/icons/contacts/linkedin.png' alt'linkedin icon'/></i>"
url = "https://www.linkedin.com/in/junella-caringal/"
weight = 10

[[menu.main]]
identifier = "email"
pre = "<i><img class='contactIcon' src='/images/icons/contacts/email.png' alt'email icon'/></i>"
url = "mailto:junellacaringal@gmail.com"
weight = 20

[[menu.main]]
identifier = "gitlab"
pre = "<i><img class='contactIcon' src='/images/icons/contacts/gitlab.png' alt'gitlab icon'/></i>"
url = "https://gitlab.com/Junella"
weight = 30

[[menu.main]]
identifier = "github"
pre = "<i><img class='contactIcon' src='/images/icons/contacts/github.png' alt'github icon'/></i>"
url = "https://github.com/Junnanella"
weight = 40
